<# SpecExec bitmask helper. Pick mitigations, click Generate, get a tiny remediation .ps1. #>

Add-Type -AssemblyName PresentationFramework

$xaml = @'
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="SpecExec Bitmask Builder" Width="500" Height="480"
        WindowStartupLocation="CenterScreen" ResizeMode="CanMinimize">
    <StackPanel Margin="12">
        <TextBlock Text="Hyper-Threading" FontWeight="Bold" Margin="0,0,0,2"/>
        <StackPanel Orientation="Horizontal" Margin="0,0,0,8">
            <RadioButton x:Name="rbHtOn"  Content="Enabled"  IsChecked="True" GroupName="HT" Margin="0,0,12,0"/>
            <RadioButton x:Name="rbHtOff" Content="Disabled" GroupName="HT"/>
        </StackPanel>
        <CheckBox x:Name="cbHyperV" Content="Hyper-V host (adds MinVmVersionForCpuBasedMitigations)" Margin="0,0,0,8"/>
        <TextBlock Text="Intel / shared" FontWeight="Bold" Margin="0,0,0,2"/>
        <CheckBox x:Name="cbPriorBundle" Content="Prior CVE bundle (Spectre v2, Meltdown, SSBD, L1TF, MDS, TAA, SRBDS)"/>
        <CheckBox x:Name="cbBhi"         Content="CVE-2022-0001 BHI"/>
        <TextBlock Text="AMD" FontWeight="Bold" Margin="0,8,0,2"/>
        <CheckBox x:Name="cbAmdBtc"       Content="CVE-2022-23825 Branch Type Confusion (Retbleed-AMD)"/>
        <CheckBox x:Name="cbAmdInception" Content="CVE-2023-20569 Inception"/>
        <TextBlock Text="Output" FontWeight="Bold" Margin="0,12,0,2"/>
        <TextBlock x:Name="txtOverride" Text="FeatureSettingsOverride     = 0x00000000" FontFamily="Consolas"/>
        <TextBlock x:Name="txtMask"     Text="FeatureSettingsOverrideMask = 0x00000003" FontFamily="Consolas"/>
        <TextBlock x:Name="txtMinVm"    Text="MinVmVersionForCpuBasedMitigations = &quot;1.0&quot;" FontFamily="Consolas" Visibility="Collapsed"/>
        <TextBlock Text="Output path" FontWeight="Bold" Margin="0,12,0,2"/>
        <TextBox x:Name="tbPath" Text="C:\temp\Remediate-SpecExecCVEs.ps1"/>
        <Button x:Name="btnGenerate" Content="Generate" Height="28" Margin="0,12,0,0"/>
        <TextBlock x:Name="txtStatus" Margin="0,8,0,0"/>
    </StackPanel>
</Window>
'@

$window = [Windows.Markup.XamlReader]::Load((New-Object System.Xml.XmlNodeReader ([xml]$xaml)))
$ctl = @{}
foreach ($n in 'rbHtOn','rbHtOff','cbHyperV','cbPriorBundle','cbBhi','cbAmdBtc','cbAmdInception','txtOverride','txtMask','txtMinVm','tbPath','btnGenerate','txtStatus') {
    $ctl[$n] = $window.FindName($n)
}

function Get-State {
    $o = 0
    if ($ctl.cbPriorBundle.IsChecked)   { $o = $o -bor ($(if ($ctl.rbHtOff.IsChecked) { 0x2048 } else { 0x0048 })) }
    if ($ctl.cbBhi.IsChecked)           { $o = $o -bor 0x00800000 }
    if ($ctl.cbAmdBtc.IsChecked)        { $o = $o -bor 0x01000040 }
    if ($ctl.cbAmdInception.IsChecked)  { $o = $o -bor 0x04000040 }
    @{ Override = $o; NeedsMinVm = [bool]$ctl.cbHyperV.IsChecked }
}

function Update-Output {
    $s = Get-State
    $ctl.txtOverride.Text = "FeatureSettingsOverride     = 0x{0:X8}" -f $s.Override
    $ctl.txtMask.Text     = "FeatureSettingsOverrideMask = 0x00000003"
    $ctl.txtMinVm.Visibility = if ($s.NeedsMinVm) { 'Visible' } else { 'Collapsed' }
}

foreach ($n in 'rbHtOn','rbHtOff','cbHyperV','cbPriorBundle','cbBhi','cbAmdBtc','cbAmdInception') {
    $ctl[$n].Add_Click({ Update-Output })
}

$ctl.btnGenerate.Add_Click({
    $s = Get-State
    $hex  = "0x{0:X8}" -f $s.Override
    $path = $ctl.tbPath.Text
    $lines = @(
        "# Generated by New-SpecExecBitmask. Reboot required after applying."
        "# AMD bits per KB4072698 / KB4073119."
        "`$P = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management'"
        "`$HvP = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization'"
        "New-ItemProperty -Path `$P -Name 'FeatureSettingsOverride'     -Value $hex        -PropertyType DWord  -Force | Out-Null"
        "New-ItemProperty -Path `$P -Name 'FeatureSettingsOverrideMask' -Value 0x00000003  -PropertyType DWord  -Force | Out-Null"
    )
    if ($s.NeedsMinVm) {
        $lines += "New-ItemProperty -Path `$HvP -Name 'MinVmVersionForCpuBasedMitigations' -Value '1.0' -PropertyType String -Force | Out-Null"
    }
    try {
        $dir = Split-Path -Parent $path
        if ($dir -and -not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        Set-Content -LiteralPath $path -Value ($lines -join "`r`n") -Encoding UTF8
        $ctl.txtStatus.Text = "Wrote $path"
    } catch {
        $ctl.txtStatus.Text = "Failed: $($_.Exception.Message)"
    }
})

Update-Output
$window.ShowDialog() | Out-Null
