# OSD-ComputerSetup.ps1
# WinPE GUI for MECM OSD that collects a computer role (OU) and hostname from the
# imaging technician before the task sequence proceeds. Validates the hostname is
# exactly 8 alphanumeric characters, then queries the MECM site server via WMI to
# block reuse of an existing name. On success, sets OSDDomainOUName, OSDComputerName,
# and OSDComputerRole task sequence variables. Cancelling or closing the window exits
# with code 1630 to halt the task sequence.
#
# Prerequisites:
#   - Boot image features: WinPE-WMI, WinPE-Scripting, WinPE-NetFX, WinPE-PowerShell
#   - Launch via ServiceUI.exe in a task sequence step
#     (found in the MDT installation directory, e.g. C:\Program Files\Microsoft Deployment Toolkit\Templates\Distribution\Tools\x64\ServiceUI.exe)
#   - Companion files in the same directory: mecm.key, mecm.user, mecm.pass
#     (generated by Export-MECMCredential.ps1)

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

try {
    $tsenv = New-Object -COMObject Microsoft.SMS.TSEnvironment
} catch {
    [System.Windows.Forms.MessageBox]::Show("Failed to initialize the imaging environment.`r`n$($_.Exception.Message)","Computer Setup",[System.Windows.Forms.MessageBoxButtons]::OK,[System.Windows.Forms.MessageBoxIcon]::Error) | Out-Null
    exit 1
}

# --- MECM Site Config ---
$siteServer = 'mecm.contoso.com'
$siteCode   = 'MCM'

# --- Build credential from encrypted files ---
$keyFile  = Join-Path $PSScriptRoot 'mecm.key'
$userFile = Join-Path $PSScriptRoot 'mecm.user'
$passFile = Join-Path $PSScriptRoot 'mecm.pass'

if ((Test-Path $keyFile) -and (Test-Path $userFile) -and (Test-Path $passFile)) {
    $aesKey     = [System.IO.File]::ReadAllBytes($keyFile)
    $naaUser    = Get-Content $userFile -Raw
    $securePass = ConvertTo-SecureString (Get-Content $passFile -Raw) -Key $aesKey
    $naaCred    = New-Object PSCredential($naaUser, $securePass)
} else {
    $naaCred = $null
}

# --- Role display-name to OU DN mapping (techs see friendly role names only) ---
$roleMap = [ordered]@{
    'Legal Desktop'    = 'LDAP://OU=Desktops,OU=Legal,OU=Workstations,DC=contoso,DC=com'
    'Operations Laptop'     = 'LDAP://OU=Laptops,OU=Operations,OU=Workstations,DC=contoso,DC=com'
    'Accounting Desktop'    = 'LDAP://OU=Desktops,OU=Accounting,OU=Workstations,DC=contoso,DC=com'
    'Marketing Laptop'      = 'LDAP://OU=Laptops,OU=Marketing,OU=Workstations,DC=contoso,DC=com'
}

# --- Form Setup ---
$form = New-Object System.Windows.Forms.Form
$form.Text = "Computer Setup"
$form.StartPosition = "CenterScreen"
$form.FormBorderStyle = "FixedDialog"
$form.MaximizeBox = $false
$form.MinimizeBox = $false
$form.TopMost = $true
$form.ClientSize = New-Object System.Drawing.Size(860,220)

# --- Role Selection Label ---
$lblOU = New-Object System.Windows.Forms.Label
$lblOU.Text = "Select a role for this computer:"
$lblOU.AutoSize = $true
$lblOU.Location = New-Object System.Drawing.Point(12,12)
$form.Controls.Add($lblOU)

# --- Role ComboBox ---
$cboOU = New-Object System.Windows.Forms.ComboBox
$cboOU.DropDownStyle = "DropDownList"
$cboOU.Location = New-Object System.Drawing.Point(12,40)
$cboOU.Size = New-Object System.Drawing.Size(300,24)
[void]$cboOU.Items.AddRange([string[]]$roleMap.Keys)
$cboOU.SelectedIndex = 0
$form.Controls.Add($cboOU)

# --- Computer Name Label ---
$lblName = New-Object System.Windows.Forms.Label
$lblName.Text = "Enter the computer name:"
$lblName.AutoSize = $true
$lblName.Location = New-Object System.Drawing.Point(12,80)
$form.Controls.Add($lblName)

# --- Computer Name TextBox ---
$txtName = New-Object System.Windows.Forms.TextBox
$txtName.Location = New-Object System.Drawing.Point(12,108)
$txtName.Size = New-Object System.Drawing.Size(830,24)
$txtName.MaxLength = 8
$txtName.CharacterCasing = "Upper"
$txtName.Add_KeyPress({
    param($s, $e)
    if (-not [char]::IsLetterOrDigit($e.KeyChar) -and -not [char]::IsControl($e.KeyChar)) {
        $e.Handled = $true
    }
})
$txtName.Add_TextChanged({
    $btnOK.Enabled = ($txtName.Text.Trim() -match '^[a-zA-Z0-9]{8}$')
})
$form.Controls.Add($txtName)

# --- OK Button ---
$btnOK = New-Object System.Windows.Forms.Button
$btnOK.Text = "OK"
$btnOK.Location = New-Object System.Drawing.Point(652,150)
$btnOK.Size = New-Object System.Drawing.Size(90,30)
$btnOK.Enabled = $false
$form.AcceptButton = $btnOK
$form.Controls.Add($btnOK)

# --- Cancel Button ---
$btnCancel = New-Object System.Windows.Forms.Button
$btnCancel.Text = "Cancel"
$btnCancel.Location = New-Object System.Drawing.Point(752,150)
$btnCancel.Size = New-Object System.Drawing.Size(90,30)
$form.CancelButton = $btnCancel
$form.Controls.Add($btnCancel)

# --- OK Button Click Handler ---
$btnOK.Add_Click({
    $selectedName = [string]$cboOU.SelectedItem
    $computerName = $txtName.Text.Trim()

    if ([string]::IsNullOrWhiteSpace($selectedName)) {
        [System.Windows.Forms.MessageBox]::Show("Please select a role.","Computer Setup",[System.Windows.Forms.MessageBoxButtons]::OK,[System.Windows.Forms.MessageBoxIcon]::Warning) | Out-Null
        return
    }

    $selectedOU = $roleMap[$selectedName]

    # --- Check MECM for existing hostname ---
    try {
        $wmiParams = @{
            Namespace    = "root\sms\site_$siteCode"
            ComputerName = $siteServer
            Query        = "SELECT Name FROM SMS_R_System WHERE Name = '$computerName'"
            ErrorAction  = 'Stop'
        }
        if ($naaCred) { $wmiParams.Credential = $naaCred }

        $existing = Get-WmiObject @wmiParams

        if ($existing) {
            [System.Windows.Forms.MessageBox]::Show("The hostname '$computerName' already exists in MECM. Delete the existing record before imaging.","Computer Setup",[System.Windows.Forms.MessageBoxButtons]::OK,[System.Windows.Forms.MessageBoxIcon]::Error) | Out-Null
            return
        }
    } catch {
        $answer = [System.Windows.Forms.MessageBox]::Show("Unable to verify hostname against MECM:`r`n$($_.Exception.Message)`r`n`r`nContinue anyway?","Computer Setup",[System.Windows.Forms.MessageBoxButtons]::YesNo,[System.Windows.Forms.MessageBoxIcon]::Warning)
        if ($answer -ne [System.Windows.Forms.DialogResult]::Yes) { return }
    }

    # --- Set TS Variables ---
    $tsenv.Value("OSDDomainOUName") = $selectedOU
    $tsenv.Value("OSDComputerName") = $computerName
    $tsenv.Value("OSDComputerRole") = $selectedName

    $form.DialogResult = [System.Windows.Forms.DialogResult]::OK
    $form.Close()
})

# --- Cancel Button Click Handler ---
$btnCancel.Add_Click({
    $form.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
    $form.Close()
})

# --- Show Form ---
$result = $form.ShowDialog()

if ($result -ne [System.Windows.Forms.DialogResult]::OK) {
    exit 1630
}

exit 0
